### ISSUE TITLE
Nur UI changes

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad#101]
Main Signup page: The logo size is bigger than original size and one in PSD, please make smaller and center vertically. 
The text in white is also larger in the new design. Please make smaller. 
The buttons should be rounder, and make all the text slightly smaller (compare between the attached imaged (PSD) and (New). 
Sign in page: can you make the text of social logins Roman instead of Bold? and make the text and icons slightly smaller? 
Sign in bug: when you sign in through Twitter or Google (didn't get to try FB - unable to log in), while the page is loading and there is not loading indication (please add), a form page with email and password shows for a couple of seconds until the sign in works. Please make sure this does not show. 
When free-trial expires:  Please make sure that the text in the purple ribbon changes to: اضغط هنا لتفعيل اشتراكك الشهري في "أبجد بلا حدود"! 
When free-trial expires:  Please make sure to remove the line saying: "شهر كامل مجانا", the text in the golden button changes to: أعد تفعيل اشتراكك الشهري, and the text under the button becomes: ٥.٩٩ دولار شهرياً ويمكنك التوقف في أي لحظة. من خلال اشتراكك الشهري في أبجد بلا حدود ستتمكن من قراءة آلاف الكتب كما تشاء بسعر الكتاب الواحد
Subscribe page: please remove the black line on the left side, this is just an error in the PSD because the white background didn't fit the frame. Also please center everything in the page vertically and horizontally. The text under the title needs to be centered with the title, and the text under it need to be centered with it. The spacing above and under the the check points should be equal. (check the PSD image attached). 
Popup: decrease the opacity of the transparent black layer under the popup around 10%. As for the timing, pop-up shows to user after they spend 2 minutes on the app during their first session (given they are not on the reader, if they are on the reader), if they don't exit app after leaving reader, show popup after 2 seconds. If users spends less than 2 minutes, or exits the reader before seeing pop-up, show the pop-up first thing during second session. Let it appear after all books load (around 2 seconds from signing in).

**Comment by Shimaa-Hassan** [comment]
Loading UI: White page with indicator centered in the middle and we can say جاري التسجيل or جاري الدخول

**Comment by Shimaa-Hassan** [comment]
@Nur-alfayez 
"As for the timing, pop-up shows to user after they spend 2 minutes on the app during their first session (given they are not on the reader, if they are on the reader), if they don't exit app after leaving reader, show popup after 2 seconds. If users spends less than 2 minutes, or exits the reader before seeing pop-up, show the pop-up first thing during second session. Let it appear after all books load (around 2 seconds from signing in)."

About this we make this by this scenerio:
After all book load  + 2 min spent in app we show popup only in All Books page.

is it acceptable for Now ?

**Comment by Shimaa-Hassan** [comment]
@Nur-alfayez  for other scenerios please open separate issue for this.

**Comment by Nur-alfayez** [comment]
@Shimaa-Hassan not necessarily in all books page in session one. Basically like this: 

User in session 1: 

Spends 2 minutes on app, not on reader (readying a book), at any page, show popup. 

User in session 2: (did not get the popup in session 1)

All books load in all books page (2 seconds), show pop up. 

Does this make sense?

**Comment by Shimaa-Hassan** [comment]
@Nur-alfayez skip test the popup scenario for Now as I solve some issues in it.

**Comment by Nur-alfayez** [comment]
(y)

**Comment by Nur-alfayez** [comment]
@Shimaa-Hassan we made some changes on the popup/subscribe page title, please find attached  JPG. The only thing that needs to be changed is the text inside the red box in the JPG. The change is for both the popup and the subscribe page. 

I'll send the PSD in email. 

Also found a UX bug in iOS popup, please find attached too. 
![popup subscribe](https://user-images.githubusercontent.com/29916678/27994381-62a241a6-64c5-11e7-863d-80dbca2aa3ba.jpg)
![bug](https://user-images.githubusercontent.com/29916678/27994394-bde41ca6-64c5-11e7-9502-cf12583831e2.png)

**Comment by Shimaa-Hassan** [comment]
@Nur-alfayez  I discovered that popup not shown after 2 min in release although it shown in debug (this is due to opened bug in android because 2 min is long timer).
So I will make another solution for this if problem not solved we should decrease 2 min time.

**Comment by Nur-alfayez** [comment]
Hey Shimaa,

You can decrease anyway, would 1:30 min solve it?

**Comment by Nur-alfayez** [comment]
@Shimaa-Hassan for the popup, please make it show after 1 minute in session one, and if user does not see it on session one, show on session two after 10 seconds. I'll get back to you on other changes here in a bit

**Comment by Nur-alfayez** [comment]
For the subscribe page, please make sure the words Abjjad Bela 7odood are taken as an image similar to the image attached. 

الكتروني should be إلكتروني

![subscribe](https://user-images.githubusercontent.com/29916678/28112612-53f9b168-6702-11e7-8bad-9b70b32d82f9.jpg)

**Comment by Nur-alfayez** [comment]
Please center the text under the button. 

![img_5281](https://user-images.githubusercontent.com/29916678/28112721-cf051d5c-6702-11e7-952a-deb0511f70dd.png)
![img_5282](https://user-images.githubusercontent.com/29916678/28112722-cf075bee-6702-11e7-9e42-de239f726c16.png)

**Comment by Nur-alfayez** [comment]
Do social SDKs allow for Arabic authentication process?

**Comment by Nur-alfayez** [comment]
For the error messages, please change the one where a user uses an existing email to create a new account to: 

تم استخدام هذا البريد الإلكتروني من قبل، قم بتسجيل دخول لحسابك أو استخدم بريد إلكتروني مختلف 

**For a later stage,** these error messages should show as a text under the field on inside it (like default error messages) not as popup.

**Comment by Nur-alfayez** [comment]
For the error messages, please change the one where a user uses an existing email to create a new account to: تم استخدام هذا البريد الإلكتروني من قبل، قم بتسجيل دخول لحسابك من خلال هذا البريد الإلكتروني أو استخدم بريد إلكتروني مختلف لإنشاء حساب جديد

The text size is similar to the text inside the attached popup message (not the title, the body). 

And in this error popup only, add 2 call to actions as follow:  

سجل دخول لحسابك                 أنشئ حساب جديد

The one on the right takes them to the login page, and the one on the left closes the popup and refreshes the page. 

![bd5fed03-2c73-444d-887c-2d0c1536e2c5](https://user-images.githubusercontent.com/29916678/28113332-d080682e-6704-11e7-8400-100905639947.jpeg)
--

**Comment by Shimaa-Hassan** [comment]
@Nur-alfayez We skip changing alert text size. because later we will improve alert UI.

**Comment by Nur-alfayez** [comment]
No worries Shimaa

**Comment by Nur-alfayez** [comment]
@Shimaa-Hassan, after testing the Android, here are my comments: 

- on the log in page, the "did you forget your password" is a text not a clickable link
- in signup error messages, the popup that appears if you use an email already registered, please make the 2 call to actions as links (blue or orange - the same default color you use in other links in app)

**Comment by Shimaa-Hassan** [comment]
- what is the UI for forget password ? is it old one ?
- Please any change in styling of error popup make it in the next release because we will change it totally and use another UI popup. or customize it because all is appeared is the default popup and need customization.

**Comment by Nur-alfayez** [comment]
- what is the UI for forget password ? is it old one ? 

Yes old one. 

- Please any change in styling of error popup make it in the next release because we will change it totally and use another UI popup. or customize it because all is appeared is the default popup and need customization.

Sure no worries. 
--

**Comment by Nur-alfayez** [comment]
For iOS, if we can extend the time that the popup shows on second session to 10 second as its showing immediately now. But its not "urgent", only if its easily done before release.

**Comment by Shimaa-Hassan** [comment]
Ok also I currently fix issue related to popup as it appeared again when user cancel it .
