### ISSUE TITLE
the links for privacy policy and terms,

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad#102]
one more thing, the links for privacy policy and terms, used to appear in the sign in and sign up pages. Please check the current app for that as IOS would reject the app if they didn't see it somewhere.

**Comment by MahmoudAliIbrahim** [comment]
done

**Comment by EmanHylooz** [comment]
IOS: tested and worked

**Comment by EmanHylooz** [comment]
Android: Testing and Working
