### ISSUE TITLE
free-trial expires

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad#106]
When free-trial expires: Please make sure that the text in the purple ribbon changes to: اضغط هنا لتفعيل اشتراكك الشهري في "أبجد بلا حدود"!
When free-trial expires: Please make sure to remove the line saying: "شهر كامل مجانا", the text in the golden button changes to: أعد تفعيل اشتراكك الشهري, and the text under the button becomes: ٥.٩٩ دولار شهرياً ويمكنك التوقف في أي لحظة. من خلال اشتراكك الشهري في أبجد بلا حدود ستتمكن من قراءة آلاف الكتب كما تشاء بسعر الكتاب الواحد

**Comment by EmanHylooz** [comment]
In IOS: Tested and Worked.

**Comment by EmanHylooz** [comment]
In Android: Tested and Worked.
