### ISSUE TITLE
Sign in/Sign Up through Facebook/Google/Twitter on IOS

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad#108]
We need to make sure all those scenarios are tested: 

**Sign Up (A new account) that it asks for authentication for first time and opens app not web and the loading effect while signing up is correct (جاري تسجيل الدخول):** 
1. On Facebook 
2. On Twitter 
3, On Google  

ٍ**Sign In (An old account) that it does not ask for authentication as this is not the first time and opens app not web and the loading effect while signing up is correct (جاري تسجيل الدخول):** 
1. On Facebook 
2. On Twitter 
3, On Google

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan is it ready for testing?

**Comment by Shimaa-Hassan** [comment]
Yes

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan Everything is perfect here (Y)

**Comment by EmanHylooz** [comment]
It is giving خطأ غير معرّف

**Comment by Shimaa-Hassan** [comment]
Release in progress.... i solved it

**Comment by EmanHylooz** [comment]
Great. Let us know when release is ready.

**Comment by Shimaa-Hassan** [comment]
1.5.8 Release

**Comment by EmanHylooz** [comment]
All good.
