### ISSUE TITLE
Sign in/Sign Up through Facebook/Google/Twitter on Android

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad#109]
We need to make sure all those scenarios are tested: 

**Sign Up (A new account) that it asks for authentication for first time and opens app not web and the loading effect while signing up is correct (جاري تسجيل الدخول):** 
1. On Facebook 
2. On Twitter 
3, On Google  

ٍ**Sign In (An old account) that it does not ask for authentication as this is not the first time and opens app not web and the loading effect while signing up is correct (جاري تسجيل الدخول):** 
1. On Facebook 
2. On Twitter 
3, On Google

**Comment by MahmoudAliIbrahim** [comment]
@EmanHylooz  regarding facebook login opens a webview  , please provide me with your device details , because it works well in all test devices here ..

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan is it ready for testing?

**Comment by EmanHylooz** [comment]
**1. Sign up through email** 
- Click sign up through email 
- Fill in all the fields except for the gender 
- Click تسجيل 
- Nothing happens, click it again it will proceed with the sign up. 
(It should work from first click, as the gender is optional and can be left empty) 

**2. Sign up through Facebook**
- I logout from the facebook app and web in the android from my old user
- Logged in to facebook through a new user that I created here: https://developers.facebook.com/apps/957560124273468/roles/test-users/
- I logged in with this new user on facebook app and web in my android 
- In abjjad, I clicked sign up with facebook 
- It opened the web and asked me to fill in username and password.  
![screenshot_20170710-153733](https://user-images.githubusercontent.com/6830380/28116689-d9e5491c-6712-11e7-9a3e-6b544ca231c3.png)

**3. Sign in and Sign up through google + is not working** 
For the sign in, it is just sending me back to the sign in page again. 
For the sign up, it is taking permission, then sending me back to the sign in page without doing anything.

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan @MahmoudAliIbrahim 
Dismiss the facebook one, I updated the facebook app and did  so many trials till finally worked to open the app. 

We have two bugs left here: 

**1. Sign up through email**

Click sign up through email
Fill in all the fields except for the gender
Click تسجيل
Nothing happens, click it again it will proceed with the sign up.
(It should work from first click, as the gender is optional and can be left empty)

**2. Sign in and Sign up through google + is not working**
For the sign in, it is just sending me back to the sign in page again.
For the sign up, it is taking permission, then sending me back to the sign in page without doing anything.

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan I sent you an email with a video attached to see what exactly happens on google + connect with me

**Comment by Shimaa-Hassan** [comment]
@EmanHylooz In this release I make alert if google sign in error happened so please take screenshot from error and send it to me.

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan @MahmoudAliIbrahim 
The two bugs are still there: 

**1. Sign up through email**

Click sign up through email
Fill in all the fields except for the gender
Click تسجيل
Nothing happens, click it again it will proceed with the sign up.
(It should work from first click, as the gender is optional and can be left empty)


**2. Sign in and Sign up through google + is not working**
No error messages appearing, the app is just crashing.

**Comment by MahmoudAlyIbrahim** [comment]
@EmanHylooz For Sign up throught email , is this happens every time, or it was one time issue ?

**Comment by EmanHylooz** [comment]
@MahmoudAliIbrahim everytime

**Comment by EmanHylooz** [comment]
@MahmoudAliIbrahim @Shimaa-Hassan dismiss the "Sign up through email" and focus on Google+ crash
