### ISSUE TITLE
Support My Subscriptions 

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad#11]
You can open WebView to Abjjad web Settings page.

**Comment by EmanHylooz** [comment]
The page اشتراكي to be native from IOS not web view

**Comment by EmanHylooz** [comment]
When the user is subscribed from the web (through credit card, or paypal), then open the screen اشتراكي  from the app, then clicks on ألغوا اشتراكي الشهري nothing happens. 
Correct scenario: it should cancel the subscription and return the user back to the in app purchase page that tell him اشترك (just like what happens in web). 

To test those scenarios you can use those users on staging: 
subscribe from web credit
eman3@abjjad.com
123456

subscribe from web paypal
mona12@gmail.com
eman12

![img_5025](https://cloud.githubusercontent.com/assets/6830380/22866461/bc352aa8-f17f-11e6-97bc-4b1853eabf6d.PNG)
![img_5026](https://cloud.githubusercontent.com/assets/6830380/22866460/bc354fb0-f17f-11e6-9579-fe05841fc0e3.PNG)
![img_5027](https://cloud.githubusercontent.com/assets/6830380/22866459/bc349c00-f17f-11e6-8084-f3dc3519609d.PNG)

**Comment by EmanHylooz** [comment]
Thank you for your response. Upon further review, we found that your app is not in compliance with 3.1.2, from the screenshots we can see that the app still missing the information about the auto-renewable nature of the subscription :

– Subscription automatically renews unless auto-renew is turned off at least 24-hours before the end of the current period
– Account will be charged for renewal within 24-hours prior to the end of the current period, and identify the cost of the renewal
– Subscriptions may be managed by the user and auto-renewal may be turned off by going to the user's Account Settings after purchase
– Any unused portion of a free trial period, if offered, will be forfeited when the user purchases a subscription to that publication, where applicable

Note: I will provide you with the Arabic text to be added at the end of the subscription page as extra text. 

![img_2183](https://cloud.githubusercontent.com/assets/6830380/23411385/d4d16f88-fdda-11e6-9774-c652b43bdd22.PNG)
