### ISSUE TITLE
Add Subscribe shortcuts

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad#12]
Subscription shortcut should add in Electronic Books page, All Books page and Settings page

**Comment by EmanHylooz** [comment]
I can only see it in the settings page, is it added to All books and My library page?

**Comment by Shimaa-Hassan** [comment]
Yes. but u didn't take this release yet :)

**Comment by EmanHylooz** [comment]
Also some enhancement will be communicated here, as Nur might also suggest change in text and color of the background. Will send you the enhancement once ready. 

But the problem of the white area in top appeared here while I was browsing, here are some screen shots: 
![img_5037](https://cloud.githubusercontent.com/assets/6830380/22968929/28718b02-f375-11e6-974d-a089af431fdc.PNG)
![img_5038](https://cloud.githubusercontent.com/assets/6830380/22968930/28750c46-f375-11e6-866a-7ad6f68a80dc.PNG)

**Comment by Shimaa-Hassan** [comment]
"But the problem of the white area in top appeared here while I was browsing, here are some screen shots:" this is not the problem the real problem is "All screens in app get in full screen after open book reader #29". we will solve it by return app to normal screen not full screen after browsing.

**Comment by EmanHylooz** [comment]
Oh okay got you, then we will leave this only for the enhancement needed once I get it from Nur for the text phrasing.

**Comment by EmanHylooz** [comment]
For the user who is not subscribed, to show this message: 
This is for user with subscription statues = (0,3,4,5)

Text: ابدأ بتجربة "أبجد بلا حدود" لتقرأ كافة الكتب الإلكترونيّة!
![unnamed 1](https://cloud.githubusercontent.com/assets/6830380/23105967/62b86c18-f6ef-11e6-84e4-f8c6b6fa14ea.png)

When the user subscribes: 
This is for user with subscription status = (1.2.6)
Text: أنت الآن مشترك في "أبجد بلا حدود"... استمتع بقراءة ما يحلو لك!
![2](https://cloud.githubusercontent.com/assets/6830380/23106012/f8947380-f6ef-11e6-83b0-1d98addd434d.png)


Note: 
- Use same colors
- Make the height of the banner same as the one in purple

**Comment by EmanHylooz** [comment]
by the way, this banner shows when I first open the app as اشترك في أبجد althou I am a subscriber. Then it disappears when the page loads.

**Comment by EmanHylooz** [comment]
Was it done as per the excel sheet? As I cannot see it
