### ISSUE TITLE
Add support for My account

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad#17]
Edit account

**Comment by EmanHylooz** [comment]
The page "Edit Account" https://www.abjjad.com/member/editaccount to be shown as web view for those 4 sub pages: 
 تعديل الملف الشخصي
 ربط الحساب مع مواقع التواصل
إعدادات الحساب
اشتراكي* 

*This page will be hidden if the user is not subscribed at all or subscribed through Apple in app purchase, in those two cases the in app purchase will show or a page for اشتراكي from the native IOS. 
* This page will be shown only if user is subscribed through the web (no through the apple in app purchase), in that case the page اشتراكي will be a web view and the in app purchase should be hidden.

**Comment by EmanHylooz** [comment]
In Edit account web view, the edit for the picture of the user is not working. When I try to add a picture it does not open the gallery folder.
