### ISSUE TITLE
Refactor popups and buttons

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad#18]
go through all the cases in android, and copy what we have already there.

**Comment by EmanHylooz** [comment]
The functionality is perfect as per all the scenarios :) 
I might ask for some enhancements in the text (as Nur from marketing might add a couple of words or change the phrasing, only changing in text).

**Comment by Shimaa-Hassan** [comment]
Ok

**Comment by EmanHylooz** [comment]
change needed in text is sent in an email.

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan seems you did not update the pop up text? 
I sent you the updates previously in an email.

**Comment by EmanHylooz** [comment]
In [POPUP 1]
Remove the button تصفح الكتب الإلكترونية

**Comment by Shimaa-Hassan** [comment]
Done
