### ISSUE TITLE
Add the loading indicator and Abjjad Font

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad#28]

**Comment by EmanHylooz** [comment]
For any headline, use Abjjad Font that I sent (helvetica) 
While for the text in body (like for example the new pop ups) we use a font called Droid Nasekh.

**Comment by EmanHylooz** [comment]
Will the loading indicator solve the problem in All Books screen, as when it is open for the first time it shows all categories underneath each other then they start loading the books, can't they be seperate on first load and each book starts to be filled? (Check how yaqut has it when you first open their All Books screen)

![img_5051](https://cloud.githubusercontent.com/assets/6830380/23141791/30f5d15c-f7c1-11e6-9f78-18362e6431bf.PNG)

**Comment by Shimaa-Hassan** [comment]
is Droid Nasekh used before in app

**Comment by Shimaa-Hassan** [comment]
I found it.

**Comment by Shimaa-Hassan** [comment]
For the popup I used native ios alert view and  "The UIAlertView class is intended to be used as-is and does not support sub-classing. The view hierarchy for this class is private and must not be modified" so I can't change the font family

**Comment by EmanHylooz** [comment]
Okay no worries.
