### ISSUE TITLE
Change the free trial to 1 Month and Price to $5.99

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad#35]
Please change this all over the web and IOS. 
New price: $5.99. 
New free trial period: 1 Month (30 days).

**Comment by Shimaa-Hassan** [comment]
in old price in subscriptions page in web abjjad display 4.99 then 3.99 as discount. now we will display 5.99 what about the discount.

**Comment by EmanHylooz** [comment]
Remove the discount for now please :)

Best,

Eman Hylooz

Founder | Abjjad

US: +1.628.202.4417 | JO: +962.79.5402965 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by EmanHylooz** [comment]
Remove the discount for now please :)

**Comment by Shimaa-Hassan** [comment]
u will change it in another payment methods like paypal, ..... ?

**Comment by Shimaa-Hassan** [comment]
I means i changed the price in abjjad but i think some payment methods need to reconfigure new price in it ?

**Comment by EmanHylooz** [comment]
Oh good question, now in Tpay (the mobile payment) I can easily change it
from the admin of Tpay... but I thought if it is changed in abjjad it will
automatically reflect on CashU and Paypal and Visa/Master Cards.

So the three payments we need to check:
1. Checkout.com (Visa and Master)
2. Paypal
3. CashU

What shall I provide you with to be able to configure them? Or are they
configured from code?

Best,

Eman Hylooz

Founder | Abjjad

US: +1.628.202.4417 | JO: +962.79.5402965 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by EmanHylooz** [comment]
Another thing, the users who are already paying on the old price $3.99,
they should stay on old price. Is this going to be the case?


Best,

Eman Hylooz

Founder | Abjjad

US: +1.628.202.4417 | JO: +962.79.5402965 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by Shimaa-Hassan** [comment]
Another thing, the users who are already paying on the old price $3.99,
they should stay on old price. Is this going to be the case?
Yes.

**Comment by Shimaa-Hassan** [comment]
Shady will deploy today in staging so we can retest all payment methods again with old user and new one

**Comment by EmanHylooz** [comment]
I did the configuring for Paypal from our business account on paypal, 
I will check now Visa/Master and CashU.

**Comment by EmanHylooz** [comment]
Okay great idea.,

Best,

Eman Hylooz

Founder | Abjjad

US: +1.628.202.4417 | JO: +962.79.5402965 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by Shimaa-Hassan** [comment]
I did the configuring for Paypal from our business account on paypal "staging not production ?"

**Comment by EmanHylooz** [comment]
​Yeah production, I don't have access for paypal on staging. ​

Best,

Eman Hylooz

Founder | Abjjad

US: +1.628.202.4417 | JO: +962.79.5402965 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by EmanHylooz** [comment]
I guess for the Checkout.com (visa and master cards) , the price is set in the code itself not configured from their admin. Can you make sure of this? 

As for CashU, I still cannot figure it out.

**Comment by EmanHylooz** [comment]
Can you ask Sahdy to ask Tamim quickly about it? Am sure there is a quick answer so we would be 100% sure

**Comment by Shimaa-Hassan** [comment]
​Yeah production, I don't have access for paypal on staging. ​
You should not change it now in production. in staging only until push to production server.

**Comment by Shimaa-Hassan** [comment]
Ok I will send to shady

**Comment by EmanHylooz** [comment]
Okay, I undo the change on paypal production. I don;t know what is our paypal for staging. 
by the way, what you need to check from the portal itself (or the code I don't know) are: 

1. CashU 
2. Paypal 

As for checkout.com, it is from the code itself

**Comment by EmanHylooz** [comment]
I was able to test the in app purchase with new pricing and new free trial, it is all good. 

I was not able yet to test the new price and free trial from the web as I didn't get the new staging release yet.

**Comment by EmanHylooz** [comment]
I just tested on staging, all seems good. 
All payments got the new price (paypal only needs to be configured from production, which I will do after we get out the release live).
