### ISSUE TITLE
Support Apple 1 week Free Trial

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad#4]

**Comment by EmanHylooz** [comment]
- 7 days on web too (change it to 14 days)
- reflect on UI of web

**Comment by EmanHylooz** [comment]
When I subscribed through Apple, it did not show me that I have 7 days free trial before paying, and the payment shows as $3.99 not as $0 ... is this where you told me that I cannot test it unless it is on production?

**Comment by Shimaa-Hassan** [comment]
I think u tested with old user "Emanhylooz2016@gmail.com" that subscribed before in abjjad apple subscription so in this case the user will not take the free trail. in order to test this u should subscribed with new user that didn't subscribe before.

**Comment by EmanHylooz** [comment]
No I tried using a user that has bever been subscribed before (subscription status=0). 
And when I clicked on subscribe,  I got this message from apple without mentioning any free trial: 

![img_5028](https://cloud.githubusercontent.com/assets/6830380/22876920/950a1b8a-f1db-11e6-9dd4-a8d1a23d3409.PNG)

and then after subscribing, it shows that I already paid the $3.99, as per the below image: 

![img_5029](https://cloud.githubusercontent.com/assets/6830380/22876935/a8ee03c8-f1db-11e6-9ad8-7c735262aaca.PNG)

**Comment by Shimaa-Hassan** [comment]
![image](https://cloud.githubusercontent.com/assets/1814104/22878171/5ca7fd56-f1e1-11e6-8334-f3c9eacbe0cd.png)
![image](https://cloud.githubusercontent.com/assets/1814104/22878170/59fbb7e6-f1e1-11e6-8d01-e9c51a5cc943.png)

**Comment by EmanHylooz** [comment]
- Let uscheck if we can have it always in $$
- Let us check if we can have it in Arabic

**Comment by EmanHylooz** [comment]
In this one, I still need to test the free trial as I still have a problem in the signing in through the new testing account, and my iPhone is suddenly not doing in-app purchase. I will keep trying with this one.

But the enhancement we need to check is the currency, to have it always shown as $$ not in the local currency,

**Comment by EmanHylooz** [comment]
The problem solved finally :) I tested the free trial and all good :) 
What we have is only enhancement:
1. The $$
2. I noticed it is called "Subscribe monthly to abjjad" , is this something we can change? If yes, can we make it "Abjjad Unlimited" . 
3. Check if we can have it in Arabic

**Comment by Shimaa-Hassan** [comment]
1- We cannot do it, apple didn't allow us to do it
2- Now its Abjad Unlimited
3- http://stackoverflow.com/questions/7090602/itunes-connect-arabic-localization
what about making this ?

**Comment by EmanHylooz** [comment]
1. Okay no worries
2. Perfect
3. I guess they were talking here about the description in app in the apple store not for the in app purchase pop up. Anyway it seems to be not worth it to waste out tim  e on it, lets dismiss it for now.
