### ISSUE TITLE
Design changes in the looks of تحميل الكتاب button 

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad#42]
This is a change that will be provided by the marketing team. Once finalized will be shared with you.

**Comment by Shimaa-Hassan** [comment]
@EmanHylooz  Please share with me and eman the design for button

**Comment by EmanHylooz** [comment]
I shared them in the same folder as the subscribe design page: 
https://drive.google.com/drive/folders/0BxPOcIV-XyapZVI0UWQ0QzNQLVE?usp=sharing

**Comment by EmanHylooz** [comment]
We have the following views where the تحميل الكتاب button appears: 

1. The مكتبني screen (and its sub screens)
2. The كل الكتب screen (and its sub screen in المزيد)
3. The أقرأ حاليا inside the profile screen
4. The search results screen
5. The book screen 

The eBooks has three options: 
1. Free eBook (it will always show تحميل الكتاب with the Tick sign)
2. eBooks for subscription 
(it will show تحميل الكتاب with the Lock sign as long as the user's subscription status=0,4,5) 
(it will show تحميل الكتاب with the Tick sign as long as the user's subscription status=1,2,6) 

When the user clicks on تحميل الكتاب with tick, it becomes جاري التحميل  then it will become the new green اقرأ الكتاب button. 

3. No eBook: 
It used to be كيف أقرؤه and now this button will be removed from ALL views, except for the Book Screen. It will show أبلغوني عند توفره and once clicked it will show a loading then it will become سنبغلك عند توفره. 

Note: For all the views the buttons will show alone, only for the Book Screen page the button will show with some text above it.

**Comment by EmanHylooz** [comment]
Hello Shimaa, 

There is something to add here I forgot to discuss it with you, you can find it in the AI file. Which says that for every eBook (only ebooks) the cover image of the book will have a 3D effect with a page flip like this: 
and it appears in all the views that has eBooks in them. 
No worries if it cannot be done with the release of tonight, el muhem to keep in mind to do it for the next release. (This needs Eman to get you the 3d effect from the AI so you can draw it). 
![3d for ebooks](https://cloud.githubusercontent.com/assets/6830380/24331364/0563bcca-1233-11e7-9b3c-91a79dc80e77.png)

**Comment by Shimaa-Hassan** [comment]
@EmanHylooz  'أبلغوني عند توفره'  when loading what word i should change to ?

**Comment by Shimaa-Hassan** [comment]
And Read EBook  when opening what word i should change to ?

**Comment by EmanHylooz** [comment]
I don't get your question, but isn't it in the AI file? 

![buttins 2](https://cloud.githubusercontent.com/assets/6830380/24351481/246fcf92-12e6-11e7-872c-ac13f21d4b14.png)
![buttins](https://cloud.githubusercontent.com/assets/6830380/24351482/2472f2bc-12e6-11e7-8a02-53d0de561c61.png)

**Comment by EmanHylooz** [comment]
1. Remove the button أبلغوني عند توفره  from all views except for the books screen view as per the previously mentioned:
No eBook:
It used to be كيف أقرؤه and now this button will be removed from ALL views, except for the Book Screen. It will show أبلغوني عند توفره and once clicked it will show a loading then it will become سنبغلك عند توفره.

2. In the following screens, the button for the books always shows at first as أبلغوني عند توفره and then it changes into the correct button. (why is this happening now while in the current app the buttons shows instantly as تحميل الكتاب or كيف أقرؤه? Is it because you used here react native?); 

(login in the test flight app as emanll@abjjad.com/123456)
1. The المزيد in the  كل الكتب screen 
2. The أقرأ حاليا inside the profile screen and the قراءاتي when you click on عرض المزيد (here it shows first a white space then أبلغوني عند توفره then تحميل الكتاب)
3. The search results screen
4. The book screen

3. Logging using emanll@abjjad.com/123456 , go to كل الكتب screen in the أدب section and click on the book أولاد حارتنا (Iف should be سنبلغك عند توفره) , click on the book to go to its book screen, an error appears saying: حصل خطأ أثناء جلب معلومات الكتاب... I guess this is because of the new API used for voting to this book. It happens every time I vote for a book by clicking on أبلغوني عند توفره. 

4. In all the views, the buttons alignments do not match the AI file (Nur will do a call with you to explain it for placing the buttons in the right position as per the rest of the components inside the views, like the book image, the rating stars, the reading bar).

**Comment by EmanHylooz** [comment]
7. I just noticed a bug in the button. Download an ebook and then go to the book's screen page. Click on اقرأ الكتاب from there, the ebook opens and then the app crashes and shuts down. (try it with free ebooks or non free, it crashes always).

**Comment by Shimaa-Hassan** [comment]
8. there is design bug "white space"  in read now list in profile page

**Comment by EmanHylooz** [comment]
For #8 no need to do it, because we should remove this screen and direct the user to the مكتبتي  screen when he clicks there. So we can dismiss this old screen all together, what do you think?

**Comment by EmanHylooz** [comment]
The left bugs to be solved: 

3. Logging using emanll@abjjad.com/123456 , go to كل الكتب screen in the أدب section and click on the book أولاد حارتنا (Iف should be سنبلغك عند توفره) , click on the book to go to its book screen, an error appears saying: حصل خطأ أثناء جلب معلومات الكتاب... I guess this is because of the new API used for voting to this book. It happens every time I vote for a book by clicking on أبلغوني عند توفره.

4. In all the views, the buttons alignments do not match the AI file (Nur will do a call with you to explain it for placing the buttons in the right position as per the rest of the components inside the views, like the book image, the rating stars, the reading bar). **<-- This is later on when Nur calls you for final small changes in design.**

7. I just noticed a bug in the button. Download an ebook and then go to the book's screen page. Click on اقرأ الكتاب from there, the ebook opens and then the app crashes and shuts down. (try it with free ebooks or non free, it crashes always). Same crash happens if I click on اقرأ الكتاب from the مكتبتي screen in the sub screens: يقرأ حاليا و قرأته و سأقرؤه
@Shimaa-Hassan do you have a log for the crashes happening on test flight app? As now the ebook is crashing everywhere which is weird. I am using those credentials: book@gmail.com/123456 ... and everytime I click on اقرأ الكتاب for the books that I have them downloaded (you can find them all in the list أقرؤه حاليا) which are either free ebooks or books I have buy individually.
If there is a log for the crash would be easier to debug it.

8. When the user in profile page clicks on عرض المزيد  under اقرأ حاليا redirect the user to the مكتبيتي sub screen "يقرأ حاليا" ... and if the user clicks on عرض المزيد in the profile page under the section  قرأته سأقرؤه redirect the user  to the مكتبيتي sub screen "قرأته". <-- This way the bug of white space doesn not need to be solved because this old screen to be dismissed all together

**Comment by EmanHylooz** [comment]
3. Solved.
4. Pending the call with Nur.
5. Not Solved - Crash is still there.
6. (This page is crashing now, when clicking on عرض المزيد .. the app shuts down). Instead of solving it, dismiss the whole screen and do the following: 
When the user in profile page clicks on عرض المزيد under اقرأ حاليا redirect the user to the مكتبيتي sub screen "يقرأ حاليا" ... and if the user clicks on عرض المزيد in the profile page under the section قرأته سأقرؤه redirect the user to the مكتبيتي sub screen "قرأته". <-- This way the bug of white space doesn not need to be solved because this old screen to be dismissed all together
7. Done.

**Comment by EmanHylooz** [comment]
Bugs that showed after the 3D cover in the lates test flight, they weren't there before: 
Sign in through emanll@abjjad.com/123456

1. The الكتب page became heavy, clicking on any book image or on المزيد or تحميل الكتاب or the books genres does not respond instantly. It takes time to respond, or does not respond at all. Sometimes causing the app to crash. 
2. The الكتب page, the horizontal scroll for each genre does not always load more books on scrolling horizontally, and does not even show that is loading. 
3. The مكتبتي screen became very heavy, switching between the views takes time till it loads (either by scrolling or by clicking on the screen title such as سأقرؤه). Sometimes the screens hangs and does not switch.
4. The search results in the app do not match the ones on web. Try this search http://st.abjjad.com/search?kw=%D8%BA%D8%B3%D8%A7%D9%86+%D9%83%D9%86%D9%81%D8%A7%D9%86%D9%8A which searching for غسان كنفاني  
5. When I am not subscribed, then I subscribe through in app purchase. Some eBooks still shows the LOCK sign on تحميل الكتاب and when clicking on it says يحب تجديد الإشتراك (in addition to the old bug, which is the banner at top stays purple and does not turn into green till i restart the app). 
6. In الكتب screen, when I click on book image and go to book screen, then go back to الكتب screen, the book will be highlighted (same thing happens to the genres).

**Comment by EmanHylooz** [comment]
![img_0001](https://cloud.githubusercontent.com/assets/6830380/24677996/7aef7fa0-1991-11e7-8efb-5caf82b1a867.PNG)
![img_0002](https://cloud.githubusercontent.com/assets/6830380/24677998/7aefc672-1991-11e7-925c-b3daf50b3533.PNG)
![img_0003](https://cloud.githubusercontent.com/assets/6830380/24677994/7aeea7b0-1991-11e7-8a93-c4866ec18fbe.PNG)
![img_0004](https://cloud.githubusercontent.com/assets/6830380/24677993/7aee9e82-1991-11e7-83fe-6e387d57769c.PNG)
![img_0005](https://cloud.githubusercontent.com/assets/6830380/24677997/7aefe95e-1991-11e7-9905-d9807b96f60e.PNG)
![img_0006](https://cloud.githubusercontent.com/assets/6830380/24677995/7aef4062-1991-11e7-8e8d-86104715c2a3.PNG)
![img_0007](https://cloud.githubusercontent.com/assets/6830380/24677999/7b141b3a-1991-11e7-8e35-62587086f5c5.PNG)
![img_0008](https://cloud.githubusercontent.com/assets/6830380/24678000/7b14bb30-1991-11e7-85a9-ec48559def47.PNG)
![img_0009](https://cloud.githubusercontent.com/assets/6830380/24678001/7b153a56-1991-11e7-8203-046402ffadb5.PNG)
![img_0010](https://cloud.githubusercontent.com/assets/6830380/24678002/7b176574-1991-11e7-8e67-547adef46b6d.PNG)

**Comment by EmanHylooz** [comment]
(performance bugs are all solved) 

The bugs left after testing the latest test flight : 

1.Memory Crash:  This page is crashing now, when clicking on عرض المزيد .. the app shuts down). 
When the user in profile page clicks on عرض المزيد under اقرأ حاليا 

2. Critical Crash:  I just noticed a bug in the button. Download an ebook and then go to the book's screen page. Click on اقرأ الكتاب from there, the ebook opens and then the app crashes and shuts down. (try it with free ebooks or non free, it crashes always). Same crash happens if I click on اقرأ الكتاب from the مكتبتي screen in the sub screens: يقرأ حاليا و قرأته و سأقرؤه

3. The search results in the app do not match the ones on web. Try this search http://st.abjjad.com/search?kw=%D8%BA%D8%B3%D8%A7%D9%86+%D9%83%D9%86%D9%81%D8%A7%D9%86%D9%8A which searching for غسان كنفاني

4. When I am not subscribed, then I subscribe through in app purchase. Some eBooks still shows the LOCK sign on تحميل الكتاب and when clicking on it says يحب تجديد الإشتراك (in addition to the old bug, which is the banner at top stays purple and does not turn into green till i restart the app). <-- We agreed not to laod the الكتب screen until we get the confirmation from apple that the user is subscribed. The loader should have a timer indication so the user would figure out that he is waiting for something.

**Comment by EmanHylooz** [comment]
For #3 I figured out what is happening, it sorted by الأحدث اصدارا while it should not. Take the sorting same as the one in web, which I guess it is by best match.

**Comment by EmanHylooz** [comment]
An extra scenario that might help you in # 2 the critical crash, search for غسان كنفاني and click on تحميل الكتاب then اقرأ الكتاب .. the app will crash.

**Comment by Shimaa-Hassan** [comment]
@EmanHylooz related to memory crashes.
this is because using multi react view (button and image react views) inside native ios lists. So for every item in list react view loaded for button and another one for image. this is high in memory. So in order to solve it we just will implement search view using react native one time view not multi views for each item. and for profile page we will go to library page when click on load more. this will solve all memory crashes including "Critical Crash"

**Comment by EmanHylooz** [comment]
Will that have any affect on the general design of each page?

**Comment by Shimaa-Hassan** [comment]
I will design new react native page same as current native one.

**Comment by EmanHylooz** [comment]
As agreed over the phone: 
1 & 2 (critical crash and memory crash) to work on it today and if there is time to get a testflight release. 
3 & 4 to work on them tomorrow and get a testflight release end of tomorrow.

**Comment by EmanHylooz** [comment]
1. Critical Crash still there 
2. The Profile Page reading list, it is solved. (one small addition needed as per the screen shot below)
3. Search results are still sorted. This time by mostly read. Screen shot below shows the default sorting needed as per the web. (basically no sorting, and works on best match) 
4. Not Yet. 

![screenshoteditpicture 1](https://cloud.githubusercontent.com/assets/6830380/24897359/5188ced6-1ea1-11e7-8a91-89bbc3e8573f.jpeg)
![screenshoteditpicture](https://cloud.githubusercontent.com/assets/6830380/24897360/518a1372-1ea1-11e7-87ce-7ca0b648ab6c.jpeg)
