### ISSUE TITLE
Support Apple restore subscription

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad#5]

**Comment by EmanHylooz** [comment]
How can I test this? 

I subscribed through in app purchase, deleted the app, then reinstalled it, and I was still subscribed. Is this it?

**Comment by Shimaa-Hassan** [comment]
the restore button is not needed by apple in subscription. it is needed only in purchase products. so to make sure about it we look at another applications and found apps that make subscription only didn't show restore button so we didn't show the button but its logic is implemented. and if for any reason app failed to deliver the user subscription status to abjjad server, we will not finish the transaction so the transaction is retried each time user open the app to deliver the user subscription status to server.

**Comment by EmanHylooz** [comment]
Understood.
