### ISSUE TITLE
Improve Write (Reviews, Quotes, ....) + Search Icon 

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad#56]
1. Implement the write (review, quotes, ...) same as how it is implemented in IOS and the icon on the dheader next to the search icon. 
2. Add a shortcut for the search icon is same places as in IOS. 

(in أبجديات  and  مكتبتي and الكتب and  التنبيهات screens).  

[https://github.com/EmanHylooz/Abjjad/issues/7](url)

**Comment by MahmoudAlyIbrahim** [comment]
done

**Comment by EmanHylooz** [comment]
1. Once the search is clicked, the keypad has to be activated by default )check IOS behavior)
