### ISSUE TITLE
Improve My library UI

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad#58]
Exactly the same as the IOS right now. 
[https://github.com/EmanHylooz/Abjjad/issues/9](url)

**Comment by EmanHylooz** [comment]
5. In مكتبتي  the + when the screens are empty is not working. (in all four screens)

**Comment by EmanHylooz** [comment]
1. When I open the ebook to read, the font is huge, and the percentage for reading is something lie 300%. (is this the new SDK update for the reader?) 
2. The tabs titles (الكتب الإلكترونية يقرأ حاليا ...الخ) are not using the correct font type, and the size has to be smaller. 
3. The font inside the buttons تحميل الكتاب  is bold, it should be Roman, And the text should be in the middle of the button. 
4. The button should be smaller (same as IOS) in the width and height. 
5. The ribbon of محاتي also the text has to be in the middle of the ribbon.

**Comment by Shimaa-Hassan** [comment]
#82
