### ISSUE TITLE
Improve Search UI

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad#6]
Search will be in Top and Global

**Comment by EmanHylooz** [comment]
1. Make the Search Icon a bit bigger (Check the search Icon inside Yaqut app)
2. Add the search Icon on top of أبجديات Screen **(and remove the old My eBooks icon)**
3. Add the search icon on top of مكتبتي Screen 
4. Add the search icon on top of التنبهات Screen **(and remove the old My eBooks icon)** 
5. The search results (please fix تحميل الكتاب button as per the below screen shot) 
![img_5014](https://cloud.githubusercontent.com/assets/6830380/22865050/da7c7cd4-f164-11e6-805a-faf933eeca40.PNG)
