### ISSUE TITLE
Refactor popups and buttons

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad#62]
Same scenarios as the one we have in IOS, the text inside the pop ups to be changed accordingly. 
Make sure to use the native pop ups in Android as the current ones has a very bad design. 
[https://github.com/EmanHylooz/Abjjad/issues/18](url)

**Comment by EmanHylooz** [comment]
1. The button loads a lot before showing the pop up, the pop up should appear directly after clicking on تحميل الكتاب 
2. When subscription status=5 (free trial expired), the pop up content is incorrect. (it shows the one for subscription status =4) 

2. The pop up used is not the standard android dialog one. (use the same as the one shown here, headline is bold and links are blue) 
![standard](https://cloud.githubusercontent.com/assets/6830380/26155417/bda728ba-3b1b-11e7-9bd1-0ff1d791c5bd.png)

**Comment by Shimaa-Hassan** [comment]
The pop up used is not the standard android dialog one. (use the same as the one shown here, headline is bold and links are blue) "Done"

**Comment by Shimaa-Hassan** [comment]
@EmanHylooz  When subscription status=5 (free trial expired), the pop up content is incorrect. (it shows the one for subscription status =4)
I want the tested account

**Comment by Shimaa-Hassan** [comment]
The button loads a lot before showing the pop up, the pop up should appear directly after clicking on تحميل الكتاب "Done"

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan 
(for free trial expired)
free@gmail.com 
password: eman12
