### ISSUE TITLE
Design changes in the looks of تحميل الكتاب button

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad#67]
Exactly the same as the final design provided by Nur and that was implemented in IOS now. 
[https://github.com/EmanHylooz/Abjjad/issues/42](url)

**Comment by EmanHylooz** [comment]
Make sure they are implemented in all the screens, with the latest design and colors (make sure the width and height are the same as IOS) .. it is currently not implemented in: 

1. The book screen
2. The profile screen 
3. The search screen 
4. The المزيد  screen 

And it has issues in font and size in the following screens: 
1. The All books screen 
2. The my library screen 

And the أبلغوني عند توفره is not implemented yet too.

**Comment by EmanHylooz** [comment]
1, When I click on  أبلغوني عند توفره  nothing happens.
2. The تحميل الكتاب  in not vertically aligned.

**Comment by Shimaa-Hassan** [comment]
The text is not vertically aligned. #84
