### ISSUE TITLE
Improve Write (Reviews, Quotes, ....) UI

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad#7]
should be in top rigth

**Comment by EmanHylooz** [comment]
1. Please change أضف إقتباسة into أضف اقتباساً (ٌRemove the hamzeh from اقتباساً)
2. Add the icon next to search icon on top of أبجديات screen 
2. Add the icon next to search icon on top of مكتبتي screen 
3. Add the icon next to search icon on top of التنبيهات screen
