### ISSUE TITLE
Show loading after login until main screen opened

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad#71]

**Comment by EmanHylooz** [comment]
And after register too.

**Comment by EmanHylooz** [comment]
1. I register a new user 
2. The loading starts 
3. Then the loading stops while I am still in the registration page and it does not log me in (but a user is created in the database) 
4. It says لا يوجد اتصال بشبكة الانترنت 
5. I have to close the app and open it again to find myself logged in

**Comment by Shimaa-Hassan** [comment]
#80
