### ISSUE TITLE
403 forbidden in android when try to download book after register new user in same mobile

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad#77]

**Comment by Shimaa-Hassan** [comment]
@EmanHylooz u remember 403 forbidden that appear when u r in egypt ? when u try to download book ? 
this happen when multi user use abjjad in same mobile. so i want to know is abjjad app available only for one user in same mobile ?

**Comment by EmanHylooz** [comment]
Hi @Shimaa-Hassan ... the condition is as the following: 

1. The same user can access his subscription through 5 different devices. 
2. The same device can have 2 different subscribers. 

So if you have a subscription (weather paid or free trial) with username X ... X can sign in form 5 devices and read ebooks, but if X tried to access a 6th device, this error will appear. 

And if you have an iPhone called ShimaaiPhone, through this iPhone you can sign in from user X and Y (subscribers or free trial) and read ebooks. 

We did this so the user won't do endless number of freetirals from the same device.
