### ISSUE TITLE
Dialog of no internet go to library keep appear

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad#85]

**Comment by MahmoudAliIbrahim** [comment]
done

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan is this ready for testing in the recent APK?

**Comment by Shimaa-Hassan** [comment]
Yes we make a solution by automatically close dialog after internet came back. 
because old developers show this dialog after request failed "may be failed because internet is slow" so we can show dialog only after 3 failed requests what is your opinion ?

**Comment by EmanHylooz** [comment]
Sounds good. We can talk more about ot over the call just to make sure I
understood correctly.
