### ISSUE TITLE
Improve My library UI

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad#9]
UI should be like Abjjad android app have Tabs (electronic books, Read Now, My Reads, .....)

change ? in tabs to My Library

**Comment by EmanHylooz** [comment]
1. The page كتبي الإلكترونية: 

(a) When Empty, please fill it with the following text:
![img_5005](https://cloud.githubusercontent.com/assets/6830380/22260806/327df4ea-e273-11e6-99cf-19bd4df57724.PNG)

(b) When filled with ebooks, make it look like exactly the ebooks screen we already have (as the one in this release is missing the progress bar and the اقرأ الكتاب.. no need to do a new one just take the old one as is):
![img_5003](https://cloud.githubusercontent.com/assets/6830380/22260908/9ec58b22-e273-11e6-8750-c2dcd8254be0.PNG)
 
(c) When the user is offline (no internet connection) he can still read the ebooks. When he tries to open abjjad while offline, this message appears (clicking on yes takes him to the old library page) please link it to the new library page instead: 
![img_5002](https://cloud.githubusercontent.com/assets/6830380/22261389/663911d2-e275-11e6-83ae-9a86870d3290.PNG)

(d) I just noticed an old bug! When I download an ebook (not free), then disconnect from the internet and  open abjjad app in IOS, I try to click اقرأ الكتاب for the ebook I downloaded it does not open (although it works for the free ebooks to open them while not connected to the internet, also it works on android). The error message is weird... "حصل خطأ أثناء إضافة التعليق". Can you please check it too?

**Comment by EmanHylooz** [comment]
2. The page يقرأ حالياً

**(a) When empty, you can use the same text we have in the IOS app when it is empty inside the "my profile" screen and just link it to the new All Books screen** 

![img_5010](https://cloud.githubusercontent.com/assets/6830380/22262400/6c302fe0-e279-11e6-9588-e3d6b566d2fd.PNG)

**(b) When filled with books... Please make it exactly like the current page we have in abjjad IOS app (without the list of أقرؤه & أنوي قرائته underneath) as the one we have in this release is missing the progress and the edit progress icon. Just take the same one we have as per this image:** 

![img_5011](https://cloud.githubusercontent.com/assets/6830380/22262945/6e7823c8-e27b-11e6-9aac-26ac67746d44.PNG)

![img_5012](https://cloud.githubusercontent.com/assets/6830380/22262959/77d52394-e27b-11e6-9397-86404179f643.PNG)

**Comment by EmanHylooz** [comment]
3. For the screens قرأته and  سأقرؤه 

(a) Empty page.. same as above... you can add the same text and link it to ِthe new all books screen. 

(b) When filled, please add the تحميل الكتاب button  under each book (and there is a black line next to the title, it should be removed)

**Comment by EmanHylooz** [comment]
(Check android when pages are filled, and do exactly the same structure when filled with books)

**Comment by Shimaa-Hassan** [comment]
@EmanHylooz  "(d) I just noticed an old bug! When I download an ebook (not free), then disconnect from the internet and open abjjad app in IOS, I try to click اقرأ الكتاب for the ebook I downloaded it does not open (although it works for the free ebooks to open them while not connected to the internet, also it works on android). The error message is weird... "حصل خطأ أثناء إضافة التعليق". Can you please check it too?"
I found where the message come from. but I need to ask about is user can read downloaded books offline ?
I think user can read free books offline but purchased books we should refresh it from server and detect if it still downloadable or no , because user can detect it and have 7 days trial download all books :) then get offline from abjjad app;
.

**Comment by EmanHylooz** [comment]
You are right! I knew about this bug before but forgot to tell you about it! Thank you for mentioning it now, it is a very important bug. 

The correct behavior is: He can read while he is offline for the purchased ebooks and free ebooks. You are right about refreshing, but we do want people to read offline and for those hackers who will notice this work around and stay offline all the time it does not matter, there won't be a lot of people e doing this and eventually they would want to read new ebooks we will add all the time :) 

So yes please solve it so it will have same behavior as in android. 

Thanks a lot :)

**Comment by EmanHylooz** [comment]
1. Same problem in the تحميل الكتاب button all over the four views. (check issue#8
(shape, corners, color, font, and height) 
2. Same problem in the behavior of the تحميل الكتاب button . It should become جاري التحميل  with loading indicator next to it then اقرأ الكتاب (Check issue#8) **(check behavior in current app)**
3. Same problem in reader when i open the book, the bottom of the app overrides the text (check issue#8)
4. When clicking on the book image in the كتبي الإلكترونية screen, it gives an error. 
5. When in كتبي الإلكترونية I click on اقرأ الكتاب and ebook opens, I flip the pages and close it, the progress bar does not get updated. I need to close the app and re-open it to see the progress **(check the correct behavior in the current app)**
6. When the كتبي الإلكترونية is empty, please remove the message we agreed on as it is causing confusion when user is subscribed. Make it the same design as the rest (like the design of اشرع في قراءة كتاب but instead write ابدأ بتحميل الكتب and link the + sign to the All Book screen. 
7. In the screen سأقرؤه make the text أضف كتاباً لقائمة قراءاتك instead
